import type { Metadata, Viewport } from 'next'
import { DM_Sans, DM_Serif_Display } from 'next/font/google'
import { Analytics } from '@vercel/analytics/next'
import { SpeedInsights } from '@vercel/speed-insights/next'
import './globals.css'
import ThemeProvider from '@/components/ThemeProvider'

const dmSans = DM_Sans({ subsets: ['latin'], variable: '--font-dm-sans' })
const dmSerif = DM_Serif_Display({ subsets: ['latin'], weight: '400', variable: '--font-dm-serif' })

const TITLE = 'ChairOS | Shop Management Software for Barbers, Salons & Tattoo Studios'
const DESCRIPTION = 'Manage your shop, retain your team, and grow your revenue with ChairOS. Built for barbershops, salons, and tattoo studios.'

export const metadata: Metadata = {
  title: TITLE,
  description: DESCRIPTION,
  manifest: '/manifest.webmanifest',
  appleWebApp: {
    capable: true,
    statusBarStyle: 'black-translucent',
    title: 'ChairOS',
  },
  openGraph: {
    title: TITLE,
    description: DESCRIPTION,
  },
  twitter: {
    card: 'summary_large_image',
    title: TITLE,
    description: DESCRIPTION,
  },
}

export const viewport: Viewport = {
  themeColor: '#4B5320',
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  viewportFit: 'cover',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${dmSans.variable} ${dmSerif.variable}`} suppressHydrationWarning>
      <head>
        {/* apple-touch-icon is auto-generated by Next.js from app/apple-icon.png */}
        <meta name="mobile-web-app-capable" content="yes" />
        {/*
          Branded instant-loading shell (web-side half of the iOS splash fix).
          This inline critical CSS paints the ChairOS mark on the very first
          paint — before JS/hydration — so the Capacitor webview shows a clean
          branded splash instead of flashing the raw unstyled page. A tiny
          inline script in <body> fades it out once the app is interactive.
          Native half still needed on the Capacitor branch: launch storyboard
          / @capacitor/splash-screen config so iOS itself shows a splash while
          the webview boots.
        */}
        <style>{`
          #chairos-splash{position:fixed;inset:0;z-index:9999;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:18px;background:#FAFAF7;transition:opacity .45s ease}
          #chairos-splash .mark{font-family:Georgia,'Iowan Old Style','Times New Roman',serif;font-size:44px;letter-spacing:-.5px;color:#1A1A18;line-height:1;margin:0}
          #chairos-splash .mark b{font-weight:400;color:#4B5320}
          #chairos-splash .bar{width:120px;height:3px;border-radius:2px;background:#E4E1D6;overflow:hidden}
          #chairos-splash .bar i{display:block;height:100%;width:40%;border-radius:2px;background:#4B5320;animation:chairos-splash-slide 1.1s ease-in-out infinite}
          @keyframes chairos-splash-slide{0%{transform:translateX(-110%)}100%{transform:translateX(300%)}}
          #chairos-splash.chairos-splash-hide{opacity:0;pointer-events:none}
          @media (prefers-color-scheme:dark){
            #chairos-splash{background:#141412}
            #chairos-splash .mark{color:#FAFAF7}
            #chairos-splash .bar{background:#2A2A26}
          }
        `}</style>
      </head>
      <body className="min-h-screen bg-warm-50 antialiased" style={{ fontFamily: 'var(--font-dm-sans)' }}>
        {/* Instant splash shell — server-rendered, painted before hydration. */}
        <div id="chairos-splash" aria-hidden="true">
          <p className="mark">Chair<b>OS</b></p>
          <div className="bar"><i /></div>
        </div>
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(){function hide(){var el=document.getElementById('chairos-splash');if(!el||el.getAttribute('data-done'))return;el.setAttribute('data-done','1');el.classList.add('chairos-splash-hide');setTimeout(function(){if(el.parentNode)el.parentNode.removeChild(el)},500)}function boot(){window.addEventListener('load',function(){setTimeout(hide,600)});if(document.readyState==='complete')setTimeout(hide,600);setTimeout(hide,6000)}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot()})()`,
          }}
        />
        <ThemeProvider>{children}</ThemeProvider>
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  )
}