import type { Metadata, Viewport } from 'next'
import { DM_Sans, DM_Serif_Display } from 'next/font/google'
import { Analytics } from '@vercel/analytics/next'
import { SpeedInsights } from '@vercel/speed-insights/next'
import './globals.css'
import ThemeProvider from '@/components/ThemeProvider'
import SplashShell from '@/components/SplashShell'

const dmSans = DM_Sans({ subsets: ['latin'], variable: '--font-dm-sans' })
const dmSerif = DM_Serif_Display({ subsets: ['latin'], weight: '400', variable: '--font-dm-serif' })

const TITLE = 'ChairOS | Shop Management Software for Barbers, Salons & Tattoo Studios'
const DESCRIPTION = 'Manage your shop, retain your team, and grow your revenue with ChairOS. Built for barbershops, salons, and tattoo studios.'

export const metadata: Metadata = {
  title: TITLE,
  description: DESCRIPTION,
  manifest: '/manifest.webmanifest',
  appleWebApp: {
    capable: true,
    statusBarStyle: 'black-translucent',
    title: 'ChairOS',
  },
  openGraph: {
    title: TITLE,
    description: DESCRIPTION,
  },
  twitter: {
    card: 'summary_large_image',
    title: TITLE,
    description: DESCRIPTION,
  },
}

export const viewport: Viewport = {
  themeColor: '#4B5320',
  width: 'device-width',
  initialScale: 1,
  // NOTE: no maximumScale / userScalable:false — disabling pinch zoom
  // breaks accessibility zoom on iOS (pre-App-Store audit finding).
  viewportFit: 'cover',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${dmSans.variable} ${dmSerif.variable}`} suppressHydrationWarning>
      <head>
        {/* apple-touch-icon is auto-generated by Next.js from app/apple-icon.png */}
        <meta name="mobile-web-app-capable" content="yes" />
        {/*
          Instant splash shell (web-side half of the iOS splash fix). The
          critical CSS paints the ChairOS mark on the very first paint --
          before JS/hydration -- and the SplashShell client component below
          fades it out through React state once the app is interactive.
          No raw DOM removal: the first attempt used an inline script that
          yanked the node out from under the App Router and broke WebView
          navigation, so this stays reconciler-driven.
        */}
        <style>{`
          #chairos-splash{position:fixed;inset:0;z-index:9999;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:18px;background:#FAFAF7;transition:opacity .45s ease}
          #chairos-splash .mark{font-family:Georgia,'Iowan Old Style','Times New Roman',serif;font-size:44px;letter-spacing:-.5px;color:#1A1A18;line-height:1;margin:0}
          #chairos-splash .mark b{font-weight:400;color:#4B5320}
          #chairos-splash .bar{width:120px;height:3px;border-radius:2px;background:#E4E1D6;overflow:hidden}
          #chairos-splash .bar i{display:block;height:100%;width:40%;border-radius:2px;background:#4B5320;animation:chairos-splash-slide 1.1s ease-in-out infinite}
          @keyframes chairos-splash-slide{0%{transform:translateX(-110%)}100%{transform:translateX(300%)}}
          #chairos-splash.chairos-splash-hide{opacity:0;pointer-events:none}
          @media (prefers-color-scheme:dark){
            #chairos-splash{background:#141412}
            #chairos-splash .mark{color:#FAFAF7}
            #chairos-splash .bar{background:#2A2A26}
          }
        `}</style>
        <noscript><style>{`#chairos-splash{display:none}`}</style></noscript>
      </head>
      <body className="min-h-screen bg-warm-50 antialiased" style={{ fontFamily: 'var(--font-dm-sans)' }}>
        <SplashShell />
        <ThemeProvider>{children}</ThemeProvider>
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  )
}